type CityType = {
  id: Number;
  country_id: Number;
  title: String | null;
  title_en: String | null;
  slug: String;
  map: String;
  timezone_id: Number;
  royalty_percent: Number;
  royalty_vacation_start: any;
  royalty_vacation_stop: any;
  created_at: String;
  updated_at: String | null;
  deleted_at: String | null;
  reservation: false;
  show_on_index: true;
  city_is_connected: true;
  manager_id: Number | null;
  video_price_classic: Number | null;
  video_price_movie_music: Number | null;
  video_price_online: Number | null;
  video_price_movie_thematic: Number | null;
  video_price_english: Number | null;
  video_price_teens: Number | null;
  video_price_corporate: Number | null;
  key: String | null;
  country: {
    id: Number;
    title: String;
    code: String | null;
    currency_id: Number;
    default_city_id: Number;
    language: String | null;
    created_at: any;
    updated_at: any;
    deleted_at: any;
  };
};

type ImageType = {
  id: Number;
  place_id: Number;
  image: String | null;
  created_at: any;
  updated_at: any;
};

type PlaceType = {
  id: Number;
  city_id: Number;
  title: String;
  address: String;
  lat: any;
  lon: any;
  special: String | null;
  option: String | null;
  covid_free: Boolean;
  anti_covid_no: Boolean;
  description: String | null;
  bar_link: String | null;
  menu: String | null;
  created_at: String | null;
  updated_at: String | null;
  deleted_at: String | null;
  city: CityType;
  images: ImageType[] | null;
};

type TemplateType = {
  id: Number;
  title: String | null;
  game_number: String | null;
  game_level: String | null;
  welcome_text: String | null;
  quote: String | null;
  description: String | null;
  block: String | null;
  hidden: Boolean;
  free: Boolean;
  game_type: Number;
  category: {
    id: Number;
    title: String;
  };
  game_underlay: String | null;
  background_pc: String | null;
  background_tablet: String | null;
  background_phone: String | null;
};

export type RadiosArray = {
  id: Number;
  game_field_id: Number;
  option_text: String;
};

export type CustomFields = {
  title: String | null;
  placeholder: String | null;
  type: Number | null;
  is_required: Boolean;
  radios: RadiosArray[];
};

export type RecordType = {
  id: Number;
  status: Number;
  game_id: String;
  team_id: Number;
  team: {
    id: Number;
    title: String;
    captain: String;
    phone: String;
    email: String;
    avg_points: any;
    avg_people: Number;
    avg_sum: Number;
    last_game_date: String;
    first_game_date: any;
    played_games: any;
    played_people: any;
    game_attendance_percentage: any;
    general_sum: Number | null;
    general_promocodes: any;
    general_certs: any;
  };
  people_count: Number;
  real_people_count: Number | null;
  certificate_id: Number | null;
  promocode_id: Number | null;
  certificate: any;
  certificate_number_people: Number;
  promocode: any;
  count_paid: Number | null;
  sum: Number | null;
  comment: String | null;
  note: any;
  transaction_number: Number | null;
  is_send_sms: Boolean;
  is_first: Boolean;
  custom_fields: Array<any>;
  created_at: any;
  updated_at: any;
};

export type GameDataType = {
  data: {
    id: String;
    country_id: Number;
    city_id: Number;
    place_id: Number;
    place: PlaceType | null;
    template_id: Number | null;
    template: TemplateType;
    title: String;
    game_type: Number;
    game_number: String | null;
    welcome_inscription: null;
    package_number: String | null;
    date: any;
    date_open_registration: any;
    description: String | null;
    block_with_text: String | null;
    quote: String | null;
    price: Number | null;
    price_type: Number | null;
    pay_method: Number | null;
    status: Number | null;
    status_hard: Boolean;
    free_enter: Boolean;
    level: String;
    time_points_limit: Number | null;
    all_registered_peoples: Number | null;
    reserved_peoples: Number | null;
    people_have_places_to_reserve: Number;
    people_reserve_no_places: Number;
    commands_have_places_to_reserve: Number;
    commands_reserve_no_places: Number;
    schedule_button_text: String | null;
    schedule_button_link: String | null;
    game_button_text: String | null;
    game_button_link: String | null;
    few_places_left: any;
    hide_registration_form_page: Boolean;
    show_on_index: Boolean;
    lang_id: Number;
    lang: {
      id: Number;
      code: String | null;
      title: String;
      created_at: any;
      updated_at: any;
      deleted_at: any;
    };
    online_city: null;
    link_contact_button: null;
    link_to_donations: null;
    link_facecast: null;
    link_results_page: null;
    banner_for_streams: null;
    banner_for_streams_desktop: null;
    banner_for_streams_tablet: null;
    banner_for_streams_mobile: null;
    qr: null;
    raunds: Array<any>;
    custom_fields: CustomFields[];
    created_at: "2024-12-12T11:46:09.000000Z";
    is_deleted: false;
    records: RecordType[];
    result: any;
    lottery_id: Number | null;
    game_quality: any;
    team_count: Number | null;
    people_count: Number | null;
    real_people_count: Number;
    need_video: Boolean;
    is_show_promo_field: Boolean | null;
    need_presentation: Boolean;
  };
};
